plugins:
  - '@trivago/prettier-plugin-sort-imports'

printWidth: 110
trailingComma: 'none'
singleQuote: true
jsxSingleQuote: true

# @trivago/prettier-plugin-sort-imports
importOrder:
  - '^@gxxc/solid-forms(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
